// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDyvk7Q2VugivCki8h9fu40HfUBBr0wHCU',
    appId: '1:542250682008:web:0661764f3a2b71ed1d72ed',
    messagingSenderId: '542250682008',
    projectId: 'donors-app-23',
    authDomain: 'donors-app-23.firebaseapp.com',
    storageBucket: 'donors-app-23.appspot.com',
    measurementId: 'G-L2BSJ5P58K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDL8Y64GU3fozMhf47h2RGL8olyBzTY80E',
    appId: '1:542250682008:android:849724c12c9adf661d72ed',
    messagingSenderId: '542250682008',
    projectId: 'donors-app-23',
    storageBucket: 'donors-app-23.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAixrzEFg-ioqhx96_eCOVPb8lp0g4CPTk',
    appId: '1:542250682008:ios:6c80c4894ab390551d72ed',
    messagingSenderId: '542250682008',
    projectId: 'donors-app-23',
    storageBucket: 'donors-app-23.appspot.com',
    iosBundleId: 'com.example.cmsc23Project',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAixrzEFg-ioqhx96_eCOVPb8lp0g4CPTk',
    appId: '1:542250682008:ios:6c80c4894ab390551d72ed',
    messagingSenderId: '542250682008',
    projectId: 'donors-app-23',
    storageBucket: 'donors-app-23.appspot.com',
    iosBundleId: 'com.example.cmsc23Project',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDyvk7Q2VugivCki8h9fu40HfUBBr0wHCU',
    appId: '1:542250682008:web:c52ccb1d41ec8a5f1d72ed',
    messagingSenderId: '542250682008',
    projectId: 'donors-app-23',
    authDomain: 'donors-app-23.firebaseapp.com',
    storageBucket: 'donors-app-23.appspot.com',
    measurementId: 'G-KX8NXKQTS1',
  );
}
